name : Build on PR
on:
  pull_request:
    branches:
      - master
jobs:
  builds:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: Setup Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '20'
  - name: Install dependencies
    run: npm install
  - name: Build
    run: npm run build